spring:
  profiles: default
  application:
    name: user-profile-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: car-wash
logging:
  level:
    root: INFO
server:
  port: 9090

  
data.transform.queue: user.review.queue
user.profile.update.queue: user.wash.count.update.queue